AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'unipept.gemspec'
    - 'vendor/**/*'
    - 'Rakefile'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# disable for now
Lint/NestedMethodDefinition:
  Enabled: false
Lint/Lint/RedundantStringCoercion:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
